name: build s0nh kernel
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup docker
        uses: docker-practice/actions-setup-docker@master
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: build
        run: |
          python3 -m pip install -r requirements.txt
          python3 wrapper bundle docker 20.0 dumpling --conan-cache --clean-docker
          python3 wrapper bundle docker 20.0 cheeseburger --conan-cache --clean-docker
      - name: form a release
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          tag: "Release"
          body: ${{ github.event.release.body }}
          prerelease: "false"
          artifacts: "bundle/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
