name: Publish light release (manual)

on:
  workflow_dispatch:
    inputs:
        IS_PRERELEASE:
          description: "Select whether this is pre-release"
          required: true
          default: "false"
          type: choice
          options:
          - "true"
          - "false"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build
        run: |
          python3 -m pip install -r requirements.txt
          python3 wrapper bundle docker 20.0 dumpling generic-slim --rom-only --clean-image
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Publish
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          tag: "s0nh-${{ steps.date.outputs.date }}"
          body: ${{ github.event.release.body }}
          prerelease: ${{ inputs.IS_PRERELEASE }}
          artifacts: "release-light/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
