name: Slim Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
        isPrerelease:
          description: "Select whether this is pre-release"
          required: true
          default: "false"
          type: choice
          options:
          - true
          - false

permissions:
  contents: write

env:
  IS_PRERELEASE: ${{ github.event.inputs.isPrerelease || false }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Build and assemble
        run: |
          python3 -m pip install poetry
          python3 -m poetry config virtualenvs.create false
          python3 -m poetry install --no-root
          python3 scripts/multi_build.py
      - name: Get current version
        id: version
        run: echo "version=$(python3 scripts/get_version.py)" >> $GITHUB_OUTPUT
      - name: Form a tag name
        id: tagname
        run: echo "tagname=v${{ steps.version.outputs.version }}.${{ github.run_number }}" >> $GITHUB_OUTPUT
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: "multi-slim"
          retention-days: 1
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Retrieve artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: "multi-slim"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ steps.tagname.outputs.tagname }}
          prerelease: ${{ env.IS_PRERELEASE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "multi-slim/*.zip"
